version: "3.9"

services:
  db:
    container_name: 'mysql'
    image: mysql:5.7
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
    ports:
      - "3306:3306"
  
  backend:
    container_name: 'go_backend'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "3030:3030"
    depends_on:
      - db

